"""add_financial_year_to_purchase_sale

Revision ID: 063712416793
Revises: 63587a5c0a6f
Create Date: 2026-06-22 12:31:38.012711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '063712416793'
down_revision: Union[str, Sequence[str], None] = '63587a5c0a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('financial_year_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchases', 'financial_years', ['financial_year_id'], ['id'])
    op.add_column('sales', sa.Column('financial_year_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'financial_years', ['financial_year_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'financial_year_id')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'financial_year_id')
    # ### end Alembic commands ###
