"""purchase_module

Revision ID: 253a9091c318
Revises: 513fa26f2a50
Create Date: 2026-06-21 11:05:04.639109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253a9091c318'
down_revision: Union[str, Sequence[str], None] = '513fa26f2a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_items')
    op.drop_table('purchases')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('voucher_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('purchases_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchases_pkey')),
    sa.UniqueConstraint('voucher_no', name=op.f('purchases_voucher_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('purchase_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('rate', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('purchase_items_product_id_fkey')),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name=op.f('purchase_items_purchase_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_items_pkey'))
    )
    # ### end Alembic commands ###
