"""add_system_code_to_ledger

Revision ID: 626f8a57acd7
Revises: 0bd7448d9ca1
Create Date: 2026-06-21 22:33:50.114833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626f8a57acd7'
down_revision: Union[str, Sequence[str], None] = '0bd7448d9ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledgers', sa.Column('system_code', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'ledgers', ['system_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ledgers', type_='unique')
    op.drop_column('ledgers', 'system_code')
        # ### end Alembic commands ###
