"""add_amount_to_transactions

Revision ID: 74c397681bc1
Revises: 063712416793
Create Date: 2026-06-22 13:01:05.936928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c397681bc1'
down_revision: Union[str, Sequence[str], None] = '063712416793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('narrations', sa.String(), nullable=True))
    op.drop_column('transactions', 'narration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('narration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'narrations')
    op.drop_column('transactions', 'amount')
    # ### end Alembic commands ###
