"""add_transaction_date

Revision ID: d0678c674e31
Revises: 5534b87a430c
Create Date: 2026-06-22 16:40:06.238367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0678c674e31'
down_revision: Union[str, Sequence[str], None] = '5534b87a430c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('bank_accounts')
    op.add_column('transactions', sa.Column('transaction_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_date')
    op.create_table('bank_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('account_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ifsc_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ledger_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], name=op.f('bank_accounts_ledger_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bank_accounts_pkey'))
    )
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('voucher_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bank_ledger_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('narration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bank_ledger_id'], ['ledgers.id'], name=op.f('payments_bank_ledger_id_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('payments_financial_year_id_fkey')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('payments_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey')),
    sa.UniqueConstraint('voucher_no', name=op.f('payments_voucher_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('voucher_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('receipt_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bank_ledger_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('narration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bank_ledger_id'], ['ledgers.id'], name=op.f('receipts_bank_ledger_id_fkey')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('receipts_customer_id_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('receipts_financial_year_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('receipts_pkey')),
    sa.UniqueConstraint('voucher_no', name=op.f('receipts_voucher_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
